on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Version
        uses: ./ # Uses an action in the root directory
        with:
          arguments: --version
      - name: Libraries
        uses: ./
        with:
          arguments: list-cores
          libraries: https://github.com/olofk/serv
  encore:
    name: give it a try
    uses: librecores/ci-fusesoc-action@v1
    with:
      core: myorg:mylib:mycore
      target: lint

